name: Build
on:
  workflow_call:
jobs:
  main:
    name: Snapshot
    runs-on: ubuntu-22.04
    steps:
      - run: mkdir ~/static
      - name: Create cache
        uses: actions/cache@v4
        with:
          path: ~/static
          key: ${{ github.run_id }}
      - uses: actions/checkout@v4
      - name: Static HTML
        run: |
          npx respec --localhost --src index.html --out ~/static/snapshot.html --haltonwarn
      - name: Check config
        id: config
        if: ${{ github.event_name == 'push'}}
        run: |
         echo "grep=false" >> $GITHUB_OUTPUT
         echo "commit=false" >> $GITHUB_OUTPUT
         if grep -q alternateFormats ./js/config.js; then
         echo "grep=true" >> $GITHUB_OUTPUT
         fi
         if grep -q commitResults ./js/config.js; then
         echo "commit=true" >> $GITHUB_OUTPUT
         fi
      - name: PDF
        if: ${{ steps.config.outputs.grep == 'true' }}
        run: |
         cp ./js/config.js config.js
         echo "module.exports = { respecConfig };" >> config.js
         echo "var window = {respecMermaid : {createFigures : null}};" | cat - config.js > temp && mv temp config.js
         cp ~/static/snapshot.html snapshot.html
         npm i puppeteer
         python3 -m http.server 8080 &
         wget https://raw.githubusercontent.com/Logius-standaarden/Automatisering/main/scripts/pdf.js
         rm -f *.pdf
         node pdf.js      
         find *.pdf
         cp *.pdf ~/static/
      - name: Clean-up
        run: |
         rm pdf.js config.js package.json package-lock.json
         rm -r node_modules
      - name: Commit
        if: ${{ steps.config.outputs.commit == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[auto] newest version of HTML and PDF'
